"""add phone number

Revision ID: 12e59801e367
Revises: c8eb13eeb4a2
Create Date: 2022-10-27 19:56:04.110268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e59801e367'
down_revision = 'c8eb13eeb4a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('users', 'phone_number')
	# ### end Alembic commands ###
