"""auto-vote

Revision ID: c8eb13eeb4a2
Revises: 9e2980902630
Create Date: 2022-10-27 19:52:02.760805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8eb13eeb4a2'
down_revision = '9e2980902630'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.alter_column('posts', 'published',
              existing_type=sa.BOOLEAN(),
              nullable=False,
              existing_server_default=sa.text('true'))
    op.alter_column('posts', 'created_at',
              existing_type=postgresql.TIMESTAMP(timezone=True),
              nullable=False,
              existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'created_at',
              existing_type=postgresql.TIMESTAMP(timezone=True),
              nullable=True,
              existing_server_default=sa.text('now()'))
    op.alter_column('posts', 'published',
              existing_type=sa.BOOLEAN(),
              nullable=True,
              existing_server_default=sa.text('true'))
    op.drop_table('votes')
    # ### end Alembic commands ###
