name: Build and Deploy code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-20.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: say hi to magne
        run: echo "hello magne"
